- name: Mount SMB share
  hosts: windows
  tasks:
    - name: Mount SMB share
      mount:
        path: /mnt/smbshare
        src: '\\\\Winserver\\Share_Binary'
        fstype: cifs
        opts: 'credentials=/home/ju/smbshare.cred'
        state: mounted

    - name: Unmount SMB share
      mount:
        path: /mnt/smbshare
        state: unmounted


#- name: Ssh configuration & SMB share on windows machine
#  hosts: windows
#  gather_facts: no # not sure about this
#  tasks:
#    - name: Ssh set up on machine
#      win_command: |
#        Set-Service -Name sshd -StartupType 'Automatic'
#        Start-Service sshd
#      become: yes
#      become_method: runas
#      become_user: admin
#      ignore_errors: yes
#      when: ansible_connection == "ssh"
#
#    - name: Create SMB share folder
#      win_file:
#        path: C:\Users\julienhourcadette\smb_share
#        state: directory
#
#    - name: SMB share
#      win_share:
#        name: share test
#        description: Just a test to see what happen
#        path: C:\smb_share
#        permissions:
#          - "Domain\\tech:CHANGE"
#          - "Domain\\design:READ"
#        state: present
