---
# tasks file for nginxConfig

- name: Install NGINX  
  become: true
  block:
    - name: Install NGINX
      ansible.builtin.package:
        name: nginx
        state: present
      register: nginx_install
    - name: Configure NGINX
      ansible.builtin.include_role:
        name: nginxinc.nginx_config
      vars:
        nginx_service_modify: true
        nginx_install: true
        nginx_start: true
        nginx_restart: true
        nginx_config_debug_output: true
        nginx_config_upload_enable: true
        nginx_config_upload:
          - src: tidy_nginx.conf
            dest: /etc/nginx/conf.d/tidy_nginx.conf          
